<div class="single-post grid" style="padding-bottom: 10px; display: none;">
    <button>Follow Us On Twitter</button>
</div>

<div style="margin: 0 auto;  border: 0px solid;">

    <div class="posts grid list">

        <div style="width: 69%; float: left;">

        <?php
        $c = 0;
        foreach($this->posts->rows() AS $key=>$row){
            $c++;
            ?>
            <div class="post" style="width: 100%;">

                <div class="post-content" style="width: 100%;">
                    <span class="post-rank"><?php echo $c; ?></span>
                    <div class="post-upvote">
                        <a class="upvote-link not-voted" href="#">
                            <i class="icon-up"></i>
                            <span>Upvote</span>
                        </a>
                    </div>
                    <div class="post-info">
                        <h3 class="post-heading">
                            <a href="/post/view/id/<?php echo $row['post_id']; ?>/title/<?php echo rawurlencode(Jien::getFriendlyUrl($row['title'])); ?>" class="post-title"><?php echo $row['title']; ?></a>
                            <span class="post-domain"><?php echo $row['domain']; ?></span>
                        </h3>
                        <p class="post-meta">
                            <span class="points">posted</span>
                            by
                                <a class="post-author" href="#"><?php echo $row['author']; ?></a>
                            <span class="post-time"><?php echo Jien::dateSince($row['created']); ?></span>
                            <span class="comments"><a class="go-to-comments" href="/posts/4JZ7b2yY9cGjhMQaf">0 comments</a></span>
                        </p>
                    </div>
                </div>
            </div>
        <?php } ?>
        <?php echo $this->pager($this->posts->pager(), 'partials/pager/pager_news.phtml'); ?>

        </div>

        <div style="float: right; width: 30%;" >
            <a class="twitter-timeline" href="https://twitter.com/search?q=%23popular" data-widget-id="409224148523552768">Tweets about "#popular"</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div>

    </div>

</div>