<div class="single-post grid" style="padding-bottom: 10px; display: none;">
    <button>Follow Us On Twitter</button>
</div>

<div style="margin: 0 auto; width: 1010px; border: 0px solid;">

    <div class="posts grid list" style="width: 75%; border: 0px solid; margin: 0; float: left;">
        <?php
        $c = 0;
        foreach($this->posts->rows() AS $key=>$row){
            $c++;
            ?>
            <div class="post" style="width: 100%;">

                <div class="post-content" style="width: 100%;">
                    <span class="post-rank"><?php echo $c; ?></span>
                    <div class="post-upvote">
                        <a class="upvote-link not-voted" href="#">
                            <i class="icon-up"></i>
                            <span>Upvote</span>
                        </a>
                    </div>
                    <div class="post-info">
                        <h3 class="post-heading">
                            <a href="/post/view/id/<?php echo $row['post_id']; ?>/title/<?php echo rawurlencode($row['title']); ?>" class="post-title"><?php echo $row['title']; ?></a>
                            <span class="post-domain"><?php echo $row['domain']; ?></span>
                        </h3>
                        <p class="post-meta">
                            <span class="points">posted</span>
                            by
                            <a class="post-author" href="#"><?php echo $row['author']; ?></a>
                            <span class="post-time"><?php echo Jien::dateSince($row['created']); ?></span>
                            <span class="comments"><a class="go-to-comments" href="/posts/4JZ7b2yY9cGjhMQaf">0 comments</a></span>
                        </p>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>

    <div style="float: right; padding-top: 8px; width: 23%;border: 0px solid; text-align: center; background-color: white; margin-left: 4px;">
        <iframe scrolling="no" style="border: 0; width: 160px; height: 600px;" src="http://coinurl.com/get.php?id=19640"></iframe>
    </div>

    <div style="clear: both; "></div>



</div>