<?php
$c = 0;
$row = $this->post->row();
?>
<style>
    .post-message a { color: #999; font-weight: normal;}
</style>
<div style=" border: 0px solid;">

    <div class="posts grid list">

        <div class="post">
            <ul class="post-actions">
                <li class="post-share desktop">
                    <a href="#" class="share-link">
                        <i class="icon-share"></i>
                        <span class="action">Share</span>
                    </a>
                </li>
                <li class="post-discuss">
                    <a class="discuss-link go-to-comments" href="<?php echo $row['url']; ?>" target="_blank">
                        <i class="icon-comment"></i>

                        <span class="action">Launch</span>
                    </a>
                </li>
                <li class="post-more mobile">
                    <a class="more-link">
                        <i class="icon-share"></i>
                        <span class="action">Text</span>
                    </a>
                </li>
            </ul>
            <div class="post-content">

                <div class="post-upvote">
                    <a class="upvote-link not-voted" href="#">
                        <i class="icon-up"></i>
                        <span>Upvote</span>
                    </a>
                </div>
                <div class="post-info">
                    <h3 class="post-heading">
                        <a href="/post/view/id/<?php echo $row['post_id']; ?>/title/<?php echo rawurlencode($row['title']); ?>" class="post-title"><?php echo $row['title']; ?></a>
                        <span class="post-domain"><?php echo $row['domain']; ?></span>
                    </h3>
                    <p class="post-meta">
                        <span class="points">2 <span class="unit">points</span></span>
                        by
                        <a class="post-author" href="/user/lauren"><?php echo $row['author']; ?></a>
                        <span class="post-time"><?php echo Jien::dateSince($row['created']); ?></span>
                        <span class="comments"><a class="go-to-comments" href="/posts/4JZ7b2yY9cGjhMQaf">0 comments</a></span>
                    </p>
                </div>
            </div>
        </div>
    </div>

    <div style="" class="post grid post-content">

        <div class="post-message" style="position: relative;">
            <?php echo $row['body']; ?>
            <div style="margin-top: 10px; text-align: left;">
                <div class="pw-widget pw-size-medium pw-counter-show">
                    <a class="pw-button-facebook"></a>
                    <a class="pw-button-twitter"></a>
                    <a class="pw-button-email"></a>
                    <a class="pw-button-post"></a>
                </div>
                <script src="http://i.po.st/static/v3/post-widget.js#publisherKey=7o1935pc152ni8vdqf7v" type="text/javascript"></script>
            </div>
        </div>

        <div style="text-align: center;">
            <script type="text/javascript">
                ( function() {
                    if (window.CHITIKA === undefined) { window.CHITIKA = { 'units' : [] }; };
                    var unit = {"publisher":"jaequery","width":550,"height":250,"sid":"scraper"};
                    var placement_id = window.CHITIKA.units.length;
                    window.CHITIKA.units.push(unit);
                    document.write('<div id="chitikaAdBlock-' + placement_id + '"></div>');
                    var s = document.createElement('script');
                    s.type = 'text/javascript';
                    s.src = 'http://scripts.chitika.net/getads.js';
                    try { document.getElementsByTagName('head')[0].appendChild(s); } catch(e) { document.write(s.outerHTML); }
                }());
            </script>
        </div>

        <div class="post-message">

            <h3>Other articles like this</h3>
            <?php
            if(!empty($row)){
                $posts = Jien::model("Post")->orderBy('rand()')->limit(5)->get();
                foreach($posts->rows() AS $key=>$row){
                    echo "<li><a style='color: rgb(74, 68, 68); font-weight: normal;' href='/post/view/id/{$row['post_id']}'>{$row['title']}</a></li>";
                }
            }
            ?>
        </div>
    </div>

</div>