<form class="form-horizontal trig_form">
	<input type="hidden" name="model" value="Site">
	<input type="hidden" name="id" value="<?php echo $this->params('id'); ?>">
    <input type="submit">
    
	<div class="row">
		<div class="col-lg-12">
			<div id="title-bar" class="page-header">
				<div class="col-lg-6">
					<h1 class="page-title">Edit Site</h1>
				</div>
				<div id="header-btns">
					<div class="inner">
                        <button class="btn btn-default trig_go" rel="/admin/sites"><span class="icon-arrow-left"></span> View List</button>
						<button type="submit" class="btn btn-default trig_save"><span class="icon-save"></span> Save</button>
						<?php if($this->params('id') != ''){ ?>
						<button rel="model=<?php echo $this->model; ?>|id=<?php echo $this->params('id'); ?>" class="btn btn-default trig_delete"><span class="icon-trash"></span> Delete</button>
						<?php } ?>
					</div><!--.inner-->
				</div><!--#header-btns.col-lg-4-->
			</div><!--#title-bar-->
		</div><!--.col-lg-12-->
	</div><!--.row-->

	<?php
	/*
	// enable when tab needed
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tab-basic" data-toggle="tab">Basic Information</a></li>
        <li><a href="#tab-advanced" data-toggle="tab">Advanced</a></li>
    </ul>
    */
    ?>

    <div class="tab-content">
    	<div class="tab-pane active" id="tab-basic">
    		<div class="row">
    			<div class="col-lg-6">
                    
            <div class="form-group">
                <label for="name" class="col-lg-4 control-label">Site Title</label>
                <div class="col-lg-8">
                    <input class="form-control" name="site_title" value="<?php echo $this->data->row("site_title"); ?>" type="text">
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-lg-4 control-label">Site Url</label>
                <div class="col-lg-8">
                    <input class="form-control" name="site_url" value="<?php echo $this->data->row("site_url"); ?>" type="text">
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-lg-4 control-label">Twitter User</label>
                <div class="col-lg-8">
                    <input class="form-control" name="twitter_user" value="<?php echo $this->data->row("twitter_user"); ?>" type="text">
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-lg-4 control-label">Twitter Widget</label>
                <div class="col-lg-8">
                    <textarea class="form-control" name="twitter_widget"><?php echo $this->data->row("twitter_widget"); ?></textarea>
                </div>
            </div>

            <div class="form-group">
                <label for="name" class="col-lg-4 control-label">Google Analytics</label>
                <div class="col-lg-8">
                    <textarea class="form-control" name="google_analytics"><?php echo $this->data->row("google_analytics"); ?></textarea>
                </div>
            </div>

    			</div><!--.col.col-lg-6-->
    		</div><!--.row-->
    	</div><!--.tab-pane-->
    </div><!--.tab-content-->
</form>