<!DOCTYPE html>
<html class="">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/themes/news/style.css">
    <meta name="fragment" content="!">
    <title><?php echo $this->title; ?></title>
    <meta name="viewport" content="initial-scale=1.0">
    <link rel="shortcut icon" href="/img/favicon.ico">
</head>
<body style="min-height: 960px;">
<div class="outer-wrapper ">
    <div id="" class="mobile-nav">
        <div>
            <ul>
                <li>
                    <a class="top" href="/top">Top</a>
                </li>
                <li>
                    <a class="new" href="/new">New</a>
                </li>
                <li>
                    <a class="digest" href="/digest">Digest</a>
                </li>
                <li>
                    <a href="/submit">Post</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-wrapper template-">
        <header class="header grid">
            <a id="mobile-menu" href="#menu" class="mobile mobile-button menu">
                <i class="icon-menu"></i>
                <span>Menu</span>
            </a>
            <ul class="nav site-nav desktop">
                <li>
                    <div class="search empty">
                        <input id="search" type="search" value="" class="search-field" placeholder="search">
                    </div>
                </li>
            </ul>
            <h1 class="logo">
                <a href="/"><?php echo $this->title; ?></a>
            </h1>
            <ul class="nav user-nav desktop">
                <li>
                    <a id="submit" class="submit button" href="/submit">Post</a>
                </li>
            </ul>
            <div class="auth-buttons">
                <div id="login-buttons" class="login-buttons-dropdown-align-right">
                    <div class="login-link-and-dropdown-list false">
                        <a class="login-link-text" id="login-sign-in-link">Subscribe to our RSS/XML</a>
                    </div>
                </div>
            </div>
        </header>

        <?php echo $this->layout()->content; ?>

    </div>
</div>
</body>

</html>
