<!DOCTYPE html>
<html class="">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="/themes/news/style.css">
    <meta name="fragment" content="!">
    <title><?php echo $this->title; ?></title>
    <meta name="viewport" content="initial-scale=1.0">
    <link rel="shortcut icon" href="/img/favicon.ico">
    <script src="/themes/admin/js/jquery.min.js"></script>
    <?php echo $this->site->row('google_analytics'); ?>
</head>
<body style="min-height: 960px;">
<div class="outer-wrapper ">
    <div id="" class="mobile-nav">
        <div>
            <ul>
                <li>
                    <a class="top" href="/top">Top</a>
                </li>
                <li>
                    <a class="new" href="/new">New</a>
                </li>
                <li>
                    <a class="digest" href="/digest">Digest</a>
                </li>
                <li>
                    <a href="/submit">Post</a>
                </li>
            </ul>
        </div>
    </div>
    <div class="content-wrapper template-">
        <header class="header grid">
            <a id="mobile-menu" href="#menu" class="mobile mobile-button menu">
                <i class="icon-menu"></i>
                <span>Menu</span>
            </a>
            <ul class="nav site-nav desktop">
                <li>
                    <div class="search empty">
                        <input id="search" type="search" value="" class="search-field" placeholder="search">
                    </div>
                </li>
            </ul>
            <h1 class="logo">
                <a href="/"><?php echo $this->title; ?></a>
            </h1>
            <ul class="nav user-nav desktop">
                <li>
                    <a class="submit button" href="/post/rss" target="_blank">RSS/XML Feed</a>
                </li>
            </ul>
            <div class="auth-buttons">
                <div id="login-buttons" class="login-buttons-dropdown-align-right">
                    <div class="login-link-and-dropdown-list false">

                    </div>
                </div>
            </div>
        </header>

        <?php echo $this->layout()->content; ?>

    </div>
</div>

<div style="clear: both;"></div>


<div class="grid" style="background-color: rgb(78, 85, 93); margin-top: 20px; color: white;">
    <div style="padding: 20px; text-align: center;">
        Copyright &copy; <?php echo date("Y"); ?> <?php echo $this->site->row('site_url'); ?>
        <?php if($this->site->row('twitter_user') != ""){ ?>
        <p>
            Made with love and care by <a target="_blank" href="http://twitter.com/<?php echo $this->site->row('twitter_user'); ?>">@<?php echo $this->site->row('twitter_user'); ?></a>
        </p>
        <?php } ?>
    </div>
</div>

<script type='text/javascript' src='//cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js'></script>
<script>
    $(document).ready(function(){
        //$.backstretch("http://www.uptownranking.com/images/bg40.jpg");
    });
</script>


</body>

</html>
